// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function DeleteRunReplay(arg1) {
  return window['go']['main']['App']['DeleteRunReplay'](arg1);
}

export function DownloadAndInstallUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1);
}

export function ExportRunReplay(arg1) {
  return window['go']['main']['App']['ExportRunReplay'](arg1);
}

export function GetAllBenchmarkProgresses() {
  return window['go']['main']['App']['GetAllBenchmarkProgresses']();
}

export function GetBenchmarkProgress(arg1) {
  return window['go']['main']['App']['GetBenchmarkProgress'](arg1);
}

export function GetBenchmarks() {
  return window['go']['main']['App']['GetBenchmarks']();
}

export function GetCustomThemeCSS() {
  return window['go']['main']['App']['GetCustomThemeCSS']();
}

export function GetDefaultSettings() {
  return window['go']['main']['App']['GetDefaultSettings']();
}

export function GetFavoriteBenchmarks() {
  return window['go']['main']['App']['GetFavoriteBenchmarks']();
}

export function GetLastScenarioScores(arg1) {
  return window['go']['main']['App']['GetLastScenarioScores'](arg1);
}

export function GetRecentRuns(arg1) {
  return window['go']['main']['App']['GetRecentRuns'](arg1);
}

export function GetRunPerformanceEvents(arg1) {
  return window['go']['main']['App']['GetRunPerformanceEvents'](arg1);
}

export function GetRunReplay(arg1) {
  return window['go']['main']['App']['GetRunReplay'](arg1);
}

export function GetRunReplayInfo(arg1) {
  return window['go']['main']['App']['GetRunReplayInfo'](arg1);
}

export function GetRunReplayStatus(arg1) {
  return window['go']['main']['App']['GetRunReplayStatus'](arg1);
}

export function GetRunStatsEvents(arg1) {
  return window['go']['main']['App']['GetRunStatsEvents'](arg1);
}

export function GetRunTrace(arg1) {
  return window['go']['main']['App']['GetRunTrace'](arg1);
}

export function GetScreenCaptureInfo() {
  return window['go']['main']['App']['GetScreenCaptureInfo']();
}

export function GetSessionTimers() {
  return window['go']['main']['App']['GetSessionTimers']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function LaunchKovaaksPlaylist(arg1) {
  return window['go']['main']['App']['LaunchKovaaksPlaylist'](arg1);
}

export function LaunchKovaaksScenario(arg1, arg2) {
  return window['go']['main']['App']['LaunchKovaaksScenario'](arg1, arg2);
}

export function OpenCustomThemeCSS() {
  return window['go']['main']['App']['OpenCustomThemeCSS']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RefreshAllBenchmarkProgresses() {
  return window['go']['main']['App']['RefreshAllBenchmarkProgresses']();
}

export function ResetSettings(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ResetSettings'](arg1, arg2, arg3, arg4);
}

export function SaveScenarioNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveScenarioNote'](arg1, arg2, arg3);
}

export function SaveSessionNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSessionNote'](arg1, arg2, arg3);
}

export function SetAutostart(arg1) {
  return window['go']['main']['App']['SetAutostart'](arg1);
}

export function SetFavoriteBenchmarks(arg1) {
  return window['go']['main']['App']['SetFavoriteBenchmarks'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartWatcher(arg1) {
  return window['go']['main']['App']['StartWatcher'](arg1);
}

export function StopWatcher() {
  return window['go']['main']['App']['StopWatcher']();
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function WriteCustomThemeCSS(arg1) {
  return window['go']['main']['App']['WriteCustomThemeCSS'](arg1);
}
